name: ai_toolkit
description: A Dart library for basic artificial intelligence algorithms and utilities.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  vector_math: ^2.1.0
  csv: ^5.0.0

dev_dependencies:
  test: ^1.24.0
